// Package codegen contains auto-generated models from OpenAPI specifications
// This file would normally be generated by oapi-codegen or similar tool
package codegen

import "time"

// Cat represents a cat entity
type Cat struct {
	CatID        *int      `json:"catId,omitempty"`
	CatName      string    `json:"catName" binding:"required,min=1,max=255"`
	CatType      string    `json:"catType" binding:"required,oneof=TYPE1 TYPE2 TYPE3 TYPE4 TYPE5"`
	Description  string    `json:"description,omitempty"`
	CatImageFile string    `json:"catImageFile,omitempty"`
	Location     *Location `json:"location,omitempty"`
}

// CatCreate represents the request body for creating a cat
type CatCreate struct {
	CatName     string `json:"catName" binding:"required,min=1,max=255"`
	CatType     string `json:"catType" binding:"required,oneof=TYPE1 TYPE2 TYPE3 TYPE4 TYPE5"`
	Description string `json:"description,omitempty"`
}

// CatUpdate represents the request body for updating a cat
type CatUpdate struct {
	CatName     *string `json:"catName,omitempty" binding:"omitempty,min=1,max=255"`
	CatType     *string `json:"catType,omitempty" binding:"omitempty,oneof=TYPE1 TYPE2 TYPE3 TYPE4 TYPE5"`
	Description *string `json:"description,omitempty"`
}

// Location represents a geographical location
type Location struct {
	Country *Country `json:"country,omitempty"`
	City    string   `json:"city,omitempty"`
	Zip     string   `json:"zip,omitempty"`
}

// Country represents a country
type Country struct {
	State string `json:"state,omitempty"`
}

// IPv4 represents an IPv4 address
type IPv4 struct {
	Value        string `json:"value" binding:"required,ipv4"`
	PrefixLength *int   `json:"prefixLength,omitempty" binding:"omitempty,min=0,max=32"`
	CatID        *int   `json:"catId,omitempty"`
}

// IPv6 represents an IPv6 address
type IPv6 struct {
	Value        string `json:"value" binding:"required,ipv6"`
	PrefixLength *int   `json:"prefixLength,omitempty" binding:"omitempty,min=0,max=128"`
	CatID        *int   `json:"catId,omitempty"`
}

// IPAddress represents both IPv4 and IPv6 addresses
type IPAddress struct {
	IPv4 *IPv4 `json:"ipv4,omitempty"`
	IPv6 *IPv6 `json:"ipv6,omitempty"`
}

// Task represents an asynchronous task
type Task struct {
	ExtID string `json:"extId"`
}

// ApiLink represents a HATEOAS link
type ApiLink struct {
	Rel  string `json:"rel"`
	Href string `json:"href"`
}

// Flag represents a feature flag
type Flag struct {
	Name  string `json:"name"`
	Value bool   `json:"value"`
}

// ApiResponseMetadata contains metadata for API responses
type ApiResponseMetadata struct {
	TotalAvailableResults *int       `json:"totalAvailableResults,omitempty"`
	Links                 []ApiLink  `json:"links,omitempty"`
	Flags                 []Flag     `json:"flags,omitempty"`
	Timestamp             *time.Time `json:"timestamp,omitempty"`
}

// CatResponse is the standard response wrapper for a single cat
type CatResponse struct {
	Data     *Cat                 `json:"data"`
	Metadata *ApiResponseMetadata `json:"metadata,omitempty"`
}

// CatListResponse is the standard response wrapper for a list of cats
type CatListResponse struct {
	Data     []Cat                `json:"data"`
	Metadata *ApiResponseMetadata `json:"metadata,omitempty"`
}

// IPv4Response is the standard response wrapper for IPv4
type IPv4Response struct {
	Data     *IPv4                `json:"data"`
	Metadata *ApiResponseMetadata `json:"metadata,omitempty"`
}

// IPv6Response is the standard response wrapper for IPv6
type IPv6Response struct {
	Data     *IPv6                `json:"data"`
	Metadata *ApiResponseMetadata `json:"metadata,omitempty"`
}

// IPAddressResponse is the standard response wrapper for IP addresses
type IPAddressResponse struct {
	Data     *IPAddress           `json:"data"`
	Metadata *ApiResponseMetadata `json:"metadata,omitempty"`
}

// TaskResponse is the standard response wrapper for tasks
type TaskResponse struct {
	Data     *Task                `json:"data"`
	Metadata *ApiResponseMetadata `json:"metadata,omitempty"`
}

// ErrorDetail represents detailed error information
type ErrorDetail struct {
	Code    string `json:"code"`
	Message string `json:"message"`
	Details string `json:"details,omitempty"`
}

// ErrorResponse is the standard error response
type ErrorResponse struct {
	Error ErrorDetail `json:"error"`
}

// ListCatsParams represents query parameters for listing cats
type ListCatsParams struct {
	Delay   *int    `form:"delay"`
	Size    *string `form:"size" binding:"omitempty,oneof=small medium large huge"`
	Version *int    `form:"version"`
	Page    *int    `form:"$page" binding:"omitempty,min=1"`
	Limit   *int    `form:"$limit" binding:"omitempty,min=1,max=1000"`
	Filter  *string `form:"$filter"`
	OrderBy *string `form:"$orderby"`
	Select  *string `form:"$select"`
	IsDummy *bool   `form:"isDummy"`
}

// GetCatStatusParams represents query parameters for getting cat status
type GetCatStatusParams struct {
	NtnxRequestID string `header:"NTNX-Request-ID" binding:"required,uuid"`
	UserRequestID string `header:"USER-Request-ID" binding:"required,uuid"`
}
